POST http://localhost:3333/videos
Content-Type: application/json

{
    "title": "Video 03",
    "description": "Esse é o video 03",
    "duration": 90
}

###

POST http://localhost:3333/videos
Content-Type: application/json

{
    "title": "Video node",
    "description": "Esse é o video node",
    "duration": 90
}
###

GET http://localhost:3333/videos?search=node


###

GET https://node-do-zero-le2o.onrender.com/videos



###

PUT http://node-do-zero-le2o.onrender.com/videos/e4d15248-b1d9-42aa-a1ec-94fdea5337d5
Content-Type: application/json

{
    //"id": "2319eb34-11f7-47d4-a194-4056b3dff2fb",
    "title": "Video node 900m",
    "description": "Esse é o video node",
    "duration": 900
}

###
 
delete http://node-do-zero-le2o.onrender.com/videos/bbea3469-7c14-4c2d-9eb6-e173ca577c21
 